-- DVS Planning · Build 10.0
-- Modello definitivo dei turni, suggerimenti e conferma/blocco.

begin;

create table if not exists public.production_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint production_suggestions_name_not_blank check (btrim(name) <> '')
);
create unique index if not exists production_suggestions_name_ci_key
  on public.production_suggestions (lower(btrim(name)));

create table if not exists public.program_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint program_suggestions_name_not_blank check (btrim(name) <> '')
);
create unique index if not exists program_suggestions_name_ci_key
  on public.program_suggestions (lower(btrim(name)));

alter table if exists public.shifts
  add column if not exists program_title text,
  add column if not exists is_client boolean not null default false,
  add column if not exists is_double_station boolean not null default false,
  add column if not exists confirmed boolean not null default false,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_by uuid,
  add column if not exists notes text,
  add column if not exists updated_at timestamptz not null default now();

-- Compatibilità con le build precedenti: il nuovo campo programma parte dal vecchio campo film.
update public.shifts
set program_title = film
where program_title is null;

alter table if exists public.shifts
  drop constraint if exists shifts_status_check;
alter table if exists public.shifts
  add constraint shifts_status_check check (status in ('definitivo', 'provvisorio'));

update public.shifts set work_type = 'SOUND' where work_type = 'SOUND DESIGN';

alter table if exists public.shifts
  drop constraint if exists shifts_work_type_check;
alter table if exists public.shifts
  add constraint shifts_work_type_check
  check (work_type in ('EDIT','ASSISTENTE','GRAFICA','COLOR','SOUND','REDAZIONE'));

alter table if exists public.shifts
  drop constraint if exists shifts_client_staff_check;
alter table if exists public.shifts
  add constraint shifts_client_staff_check check (not (is_client and staff_id is not null));

create index if not exists shifts_date_room_build10_idx
  on public.shifts (shift_date, room_code, start_time);
create index if not exists shifts_staff_date_build10_idx
  on public.shifts (staff_id, shift_date);
create index if not exists shifts_confirmed_idx
  on public.shifts (confirmed, shift_date);

-- Sale remote previste dalla vista Planning.
insert into public.rooms (code, name, sort_order)
values
  ('remoto-1', 'Remote 1', 16),
  ('remoto-2', 'Remote 2', 17),
  ('remoto-3', 'Remote 3', 18)
on conflict (code) do update
set name = excluded.name,
    sort_order = excluded.sort_order;

commit;
